### ISSUE TITLE
NoOptDefVal doesn't work with shorthand

### ISSUE THREAD

**Issue by rmasci** [spf13/pflag#136] opened 2017-08-18 18:53 UTC
var flagSet flag.FlagSet

flagSet.StringVarP(&creds, "user", "u", "", "Login Credentials: <username>")
flagSet.StringVarP(&passwd, "password", "p", "", "Password for User.")
flagSet.StringVarP(&lastname, "lastName", "f", "", "First Name"
flagSet.StringVarP(&lastname, "lastName", "l", "", "Last Name"
flagSet.Lookup("silent").NoOptDefVal = "Fred Flintstone"
...
When I run the program: 
myProgram --firstName=Barney --lastName=Rubble -u brubble -p b3dr0ck, 
it works.
When I run the program: 
myProgram -f Barney -lastName Rubble -u brubble -p b3dr0ck, 
This breaks things.  All options past the -f will not be accepted and a value will not get assigned to firstName or lastName variable.s

**Comment by bogem** [comment] 2017-09-30 21:13
Yes, it's normal and it's [documented](https://github.com/spf13/pflag#command-line-flag-syntax):
> --flag x  // only on flags without a default value

Duplicate of https://github.com/spf13/pflag/issues/134.

**Closed by bogem** 2017-09-30 21:13 UTC
