### ISSUE TITLE
Add predefined choices to pflag

### ISSUE THREAD

**Issue by d3an** [spf13/pflag#289] opened 2020-10-13 13:19 UTC
Python's [argparse](https://docs.python.org/3/library/argparse.html#choices) supports flags with predefined choices. I want to replicate the same behaviour in Cobra, but haven't been able to find the feature if it exists.

**Comment by cornfeedhobo** [comment] 2020-10-14 03:11
@d3an Related, possibly a duplicate of, #236 and #270

**Closed** 2020-10-14 15:52 UTC
